
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'flask_inference'
    scrape_interval: 15s 
    static_configs:
      - targets: ['127.0.0.1:8001'] 
